minetest.register_on_newplayer(function(player)
	player:get_inventory():add_item('main', 'default:torch 60')
	player:get_inventory():add_item('main', 'default:sword_steel')
	player:get_inventory():add_item('main', 'default:pick_stone')
	player:get_inventory():add_item('main', 'default:axe_stone')
	player:get_inventory():add_item('main', 'default:cobble 30')
	player:get_inventory():add_item('main', 'default:wood 90')
end)
